src/carts/urls.py
from django.urls import path

from .views import cart_home, cart_update, checkout_home
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name="home"),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView

# from products.views import (
#     ProductListView,
#     product_list_view,
#     ProductDetailView,
#     ProductDetailSlugView,
#     product_detail_view,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView
# )
from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view
from .views import home_page, about_page, contact_page
urlpatterns = [
    path('', home_page, name="home"),
    path('about/', about_page, name="about"),
    path('contact/', contact_page, name="contact"),
    path('login/', login_page, name="login"),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('register/guest/', guest_register_view, name="guest_register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('cart/', include("carts.urls")),
    path('products/', include("products.urls")),
    path('search/', include("search.urls")),
    path('register/', register_page, name="register"),
    path('bootstrap/', TemplateView.as_view(template_name="bootstrap/example.html")),
    # path('featured/', ProductFeaturedListView.as_view()),
    # path('featured/<int:pk>/', ProductFeaturedDetailView.as_view()),
    # path('products/', ProductListView.as_view()),
    # path('products-fbv/', product_list_view),
    # path('products/<int:pk>/', ProductDetailView.as_view()),
    # path('products/<slug:slug>/', ProductDetailSlugView.as_view()),
    # path('products-fbv/<int:pk>/', product_detail_view),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import (
    ProductListView,
    # product_list_view,
    ProductDetailView,
    ProductDetailSlugView,
    # product_detail_view,
    # ProductFeaturedListView,
    # ProductFeaturedDetailView
)
# from .views import home_page, about_page, contact_page, login_page, register_page
app_name = "products"
urlpatterns = [
    path('', ProductListView.as_view(), name="list"),
    path('<int:pk>/', ProductDetailView.as_view()),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name="detail"),
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'carts:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <a class="navbar-brand" href="{{ home_url }}">
      <img src="https://getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30"
        class="d-inline-block align-top" alt="">
      {% if brand_name %} {{ brand_name}} {% else %} CFE eCommerce {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %} active {% endif%}">
          <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == contact_url %} active {% endif%}">
          <a class="nav-link" href="{{ contact_url }}">Contact</a>
        </li>
        <li class="nav-item {% if request.path == product_list_url %} active {% endif%}">
          <a class="nav-link" href="{{ product_list_url }}">Products</a>
        </li>
        {% if  request.user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %} active {% endif%}">
          <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == register_url %} active {% endif%}">
          <a class="nav-link" href="{{ register_url }}">Register</a>
        </li>
        <li class="nav-item {% if request.path == login_url %} active {% endif%}">
          <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %} active {% endif%}">
          <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }}<i class="fa fa-shopping-cart" aria-hidden="true"></i>
</a>
        </li>        
      </ul>
      {% include "search/snippets/search-form.html" %}
    </div>
  </div>
</nav>